/** Shared inline styles — dark, compact, matching the S&S panel aesthetic
 *  (adapted from the animate panel's styles module). */

import type { CSSProperties } from 'react';

export const palette = {
  text: 'rgba(235, 235, 245, 0.92)',
  textDim: 'rgba(235, 235, 245, 0.55)',
  textFaint: 'rgba(235, 235, 245, 0.35)',
  cardBg: 'rgba(255, 255, 255, 0.04)',
  cardBorder: 'rgba(255, 255, 255, 0.08)',
  accent: '#8b7cf6',
  accentSoft: 'rgba(139, 124, 246, 0.18)',
  warn: '#e5c07b',
  danger: '#e06c75',
  chipBg: 'rgba(255, 255, 255, 0.07)',
  chipActiveBg: 'rgba(139, 124, 246, 0.28)',
};

export const styles: Record<string, CSSProperties> = {
  panel: { padding: '10px 12px 14px', color: palette.text, fontSize: 12 },
  emptyState: { padding: '14px 6px', color: palette.textDim, textAlign: 'center' },
  errorBar: {
    margin: '6px 0',
    padding: '6px 8px',
    borderRadius: 6,
    background: 'rgba(224, 108, 117, 0.12)',
    border: '1px solid rgba(224, 108, 117, 0.35)',
    color: palette.danger,
    whiteSpace: 'pre-wrap',
  },
  section: { margin: '10px 0 4px' },
  familyHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    margin: '10px 0 0',
    color: palette.textDim,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  familyDivider: {
    border: 'none',
    borderTop: `1px solid ${palette.cardBorder}`,
    margin: '14px 0 6px',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '2px 0 4px',
    borderBottom: `1px solid ${palette.cardBorder}`,
  },
  sectionTitle: { fontWeight: 600, fontSize: 12.5, letterSpacing: 0.3 },
  sectionCount: { color: palette.textFaint, fontSize: 10.5 },
  sectionSpacer: { flex: 1 },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '5px 6px',
    margin: '4px 0',
    borderRadius: 6,
    background: palette.cardBg,
    border: `1px solid ${palette.cardBorder}`,
  },
  rowName: { fontWeight: 600, minWidth: 52 },
  rowSample: {
    flex: 1,
    color: palette.textDim,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 60,
  },
  rowSampleMissing: { color: palette.warn },
  iconButton: {
    background: palette.chipBg,
    border: `1px solid ${palette.cardBorder}`,
    borderRadius: 5,
    color: palette.text,
    cursor: 'pointer',
    fontSize: 12,
    lineHeight: '18px',
    padding: '1px 7px',
  },
  iconButtonActive: {
    background: palette.chipActiveBg,
    borderColor: palette.accent,
  },
  iconButtonDisabled: { opacity: 0.35, cursor: 'default' },
  warnBadge: {
    color: palette.warn,
    fontSize: 10,
    border: `1px solid ${palette.warn}`,
    borderRadius: 4,
    padding: '0 4px',
  },
  offsetStepper: { display: 'flex', alignItems: 'center', gap: 3, color: palette.textDim, fontSize: 10.5 },
  offsetInput: {
    width: 44,
    background: 'rgba(0,0,0,0.25)',
    border: `1px solid ${palette.cardBorder}`,
    borderRadius: 4,
    color: palette.text,
    fontSize: 11,
    padding: '1px 4px',
  },
  addButton: {
    background: 'transparent',
    border: `1px dashed ${palette.cardBorder}`,
    borderRadius: 6,
    color: palette.textDim,
    cursor: 'pointer',
    fontSize: 11.5,
    margin: '4px 0 2px',
    padding: '4px 10px',
    width: '100%',
  },
  addMenu: {
    display: 'flex',
    gap: 6,
    margin: '4px 0',
  },
  addMenuItem: {
    flex: 1,
    background: palette.chipBg,
    border: `1px solid ${palette.cardBorder}`,
    borderRadius: 6,
    color: palette.text,
    cursor: 'pointer',
    fontSize: 11.5,
    padding: '4px 8px',
  },
  fxDrawer: {
    margin: '0 0 4px 12px',
    padding: '4px 8px',
    borderLeft: `2px solid ${palette.accentSoft}`,
  },
  soundDrawer: {
    margin: '0 0 4px 12px',
    padding: '4px 8px',
    borderLeft: `2px solid ${palette.accentSoft}`,
  },
  soundDrawerHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '2px 0 6px',
  },
  soundList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 4,
    maxHeight: 120,
    overflowY: 'auto',
  },
  soundItem: {
    background: palette.chipBg,
    border: `1px solid ${palette.cardBorder}`,
    borderRadius: 5,
    color: palette.text,
    cursor: 'pointer',
    fontSize: 11,
    padding: '2px 8px',
  },
  cta: {
    margin: '8px 0',
    padding: '8px 10px',
    borderRadius: 6,
    background: palette.accentSoft,
    color: palette.text,
    fontSize: 11.5,
  },
};
